version: '3'
services:
  atlant_test:
    build: .
    expose:
      - "8080"
    restart: on-failure
    networks:
      - fullstack
    env_file:
      - .env
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - atlant_test
    ports:
      - 4000:4000
    networks:
      fullstack:

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    networks:
      fullstack:
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017

networks:
  fullstack:
    driver: bridge
